### ISSUE TITLE
Missed Implementation?

### ISSUE THREAD

**Issue by dbaeza0** [AliElSaleh/DebugLogLibrary-UE4#1]
Hello! I started using your debug Library, I plan to use it mainly in C++, but I wasn't able to print Info and success logs with its respective colors (Warning and Errors do print yellow and red), I tested the blueprint functions and they work alright  in the viewport but not the console.

![Capture2](https://user-images.githubusercontent.com/50881608/78458125-3cfd4c00-766c-11ea-8865-6c8dd02d2ba6.PNG)
![Capture](https://user-images.githubusercontent.com/50881608/78457875-a67c5b00-766a-11ea-8c72-a954d0909ddd.png)

After Digging around the source of your amazing plug-in, I found:

https://github.com/AliElSaleh/DebugLogLibrary-UE4/blob/4f2b448f885551fe8ab19a2bf30840fcd2d1baa7/Plugins/Debug/Source/Debug/Private/Log.cpp#L1818-L1823

 I believe calls with green and blue colors are somehow not implemented? or am I missing something?

**Comment by dbaeza0** [comment]
Never mind after downloading the project  and lurking into the documentation, I tried many approaches before realizing that there is no clean API exposure to set log text color, any implementation would probably require to modify the engine source.

**Comment by AliElSaleh** [comment]
Yeah that's right, you cant have custom log colors. I've search for hours
on end on how to get custom log colors to work with the console with no
luck :(

I hope epic games exposes this stuff to us in future updates. Then you can
be sure that the plugin will have those too :)

Thanks,
Ali

>
